### PR TITLE
Create script to fill declaration answers for DOS5 and G12

### PR DESCRIPTION
**Pull request by bjgill**
https://crowncommercialservice.atlassian.net/browse/OST-114

For the DMP 1.5 UAT, we want to have some suppliers with complete declarations that we can use to test declaration copying. This is because the declarations are mostly stripped out from the non-production database dump.

Also add support for running scripts against the UAT environment (you'll need to provide the API bearer token in `DM_DATA_API_TOKEN_UAT`). I think this will be quicker than handing the script over to Brickendon to run.

Pulls in https://github.com/Crown-Commercial-Service/digitalmarketplace-utils/pull/721

### CODE REVIEW

**Comment by bjgill** [comment]
Example of output (shrunk to only 4 suppliers)

```
# Suppliers for g-cloud-12:
92227: 21727@user.marketplace.team
92239: 49546@user.marketplace.team
92251: 12215@user.marketplace.team
92309: 12207@user.marketplace.team

# Suppliers for digital-outcomes-and-specialists-5:
92195: 11983@user.marketplace.team
92218: 12745@user.marketplace.team
92255: 39009@user.marketplace.team
92264: 19080@user.marketplace.team

```

**Review by tberey — APPROVED** [review]

**Comment by tim-s-ccs** [comment]
For `DM_DATA_API_TOKEN_UAT`, for NFT we created the `vars/nft.yaml` file in the credentials and added the tokens there. Will there be an equivalent PR of credentials?

**Review by tim-s-ccs — APPROVED** [review]

**Comment by bjgill** [comment]
Oh no. The UAT/integration bearer tokens don't match the patterns we depend on for all other environments. That's going to make this more complicated...

**Comment by bjgill** [comment]
Added commit to pull in https://github.com/Crown-Commercial-Service/digitalmarketplace-utils/pull/722.

**Comment by bjgill** [comment]
I'm going to merge this as-is and run with bearer tokens provided via env variables.

Then I'll ask Brickendon if they could update the bearer tokens to match the expectations of our scripts.

**Pull request merged**
